name: selfish
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.7
    - pytorch
    - matplotlib
    - pillow
    - seaborn
    - pip:
        - gym
        - gin-config
        - tb-nightly
